services:
  - type: web
    name: lms-backend
    env: node
    buildCommand: cd server && npm install && node src/scripts/createInitialUsers.js
    startCommand: cd server && node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_EXPIRES_IN
        value: 30d
      - key: MONGODB_URI
        value: mongodb+srv://jitendrak4121:jitendrak4121@cluster0.iqxvxvz.mongodb.net/lms_database?retryWrites=true&w=majority

  - type: web
    name: lms-frontend
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    envVars:
      - key: NODE_ENV
        value: production 